version: '3.8'

services:
  translator_backend:
    build:
      context: ./translator_backend
    image: translator_backend_image
    container_name: translator_backend_1
    environment:
      COHERE_API_KEY: ${COHERE_API_KEY} 
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./translator_backend:/translator_backend
    restart: always
  telegram_bot:
    build:
      context: ./telegram_bot
    image: telegram_bot_image
    container_name: telegram_bot_1
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./telegram_bot:/telegram_bot
    restart: always
    command: ["bash", "-c", "pip install -r requirements.txt && python start_bot.py"]

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: veronika
      POSTGRES_PASSWORD: postgres
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: